version: "3.8"
services:
  db:
    container_name: atoll-postgres-dev
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 25432:5432
    volumes:
      - $HOME/Docker/volumes/postgres/atoll-dev:/var/lib/postgresql/data
  api:
    container_name: atoll-web-app-server-debug
    build:
      context: ./
      target: production
    image: atoll-web-app-server-debug-image
    depends_on:
      - db
    ports:
      - 28500:8500
      - 9229:9229
    environment:
      NODE_ENV: production
      ATOLL_DATABASE_URL: postgres://atoll:d0ughnutc4t@db:5432/atoll
      ATOLL_DATABASE_USE_SSL: false
      ATOLL_AUTH_KEY: x-pr0d-auth-k3y
      RESOURCE_PORT: 28500
    links:
      - db
volumes:
  db:
    driver: local
