name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Node & NPM versions
        run: |
          echo Node Version
          node --version
          echo
          echo NPM Version
          npm --version
          echo
      - name: Install NPM packages
        run: npm ci -ws
      - name: Build All Packages
        run: |
          echo Building...
          npm run build-pkg:shared
